"""Default configuration and hyperparameters."""

# Axis detection
HOUGH_THRESHOLD = 100
MIN_LINE_LENGTH = 50
MAX_LINE_GAP = 10
AXIS_ANGLE_TOLERANCE = 5  # degrees
TICK_LENGTH_THRESHOLD = 5
TICK_MAX_LENGTH = 40

# Color / background
BG_SAMPLE_BORDER = 20
BG_COLOR_DISTANCE_THRESH = 30
FOREGROUND_MIN_AREA = 10

# Data extraction
MIN_DATA_POINTS = 3
MIN_SERIES_POINTS = 30

# SSIM
SSIM_WINDOW_SIZE = 11
SSIM_SIGMA = 1.5
SSIM_K1 = 0.01
SSIM_K2 = 0.03
SSIM_THRESHOLD_SIMPLE = 0.90
SSIM_THRESHOLD_LOG = 0.80
SSIM_THRESHOLD_SCATTER = 0.75
SSIM_THRESHOLD_MULTI = 0.82

# Output
DEFAULT_DPI = 100
